version: '3'

networks:
  main_network:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/ui:/ui
    ports:
      - "3004:3004"
    networks:
      - main_network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
      - ./data:/data
    ports:
      - "3003:3003"
    networks:
      - main_network
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data
    networks:
      - main_network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    networks:
      - main_network